repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.23.1 # Utilize a versão mais recente conforme necessário
    hooks:
      - id: eslint
        args: ['--fix']
        files: '.*\\.(js|ts)$' # Alvo para verificar arquivos .js ou .ts
